query Categorias {
  Categorias {
    data {
      id
      attributes {
        nombre
        descripcion
        grupos_de_productos {
          data {
            id
            attributes {
              nombre
            }
          }
        }
        imagen {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}