query UltimosProductos {
  productos(sort: "createdAt:desc", pagination: { limit: 12 }) {
    data {
      id
      attributes {
        codigo
        nombre
        descripcion
        createdAt
        updatedAt
        imagen_principal {
          data {
            attributes {
              url
            }
          }
        }
        multimedia {
          data {
            id
            attributes {
              url
            }
          }
        }
        valoracion
        precio_venta
        precio_oferta
        en_oferta
        stock_disponible
        talla {
          data {
            attributes {
              sigla
            }
          }
        }
        grupo_de_productos {
          data {
            attributes {
              codigo
              nombre
            }
          }
        }
      }
    }
  }
}